/**
 * R4 resource categorization, transcribed from the official R4 resource list
 * (https://hl7.org/fhir/R4/resourcelist.html). Display metadata only.
 */

const MAP: Record<string, [category: string, subcategory: string]> = {
  // Foundation
  CapabilityStatement: ['Foundation', 'Conformance'],
  StructureDefinition: ['Foundation', 'Conformance'],
  ImplementationGuide: ['Foundation', 'Conformance'],
  SearchParameter: ['Foundation', 'Conformance'],
  MessageDefinition: ['Foundation', 'Conformance'],
  OperationDefinition: ['Foundation', 'Conformance'],
  CompartmentDefinition: ['Foundation', 'Conformance'],
  StructureMap: ['Foundation', 'Conformance'],
  GraphDefinition: ['Foundation', 'Conformance'],
  ExampleScenario: ['Foundation', 'Conformance'],
  CodeSystem: ['Foundation', 'Terminology'],
  ValueSet: ['Foundation', 'Terminology'],
  ConceptMap: ['Foundation', 'Terminology'],
  NamingSystem: ['Foundation', 'Terminology'],
  TerminologyCapabilities: ['Foundation', 'Terminology'],
  Provenance: ['Foundation', 'Security & Privacy'],
  AuditEvent: ['Foundation', 'Security & Privacy'],
  Consent: ['Foundation', 'Security & Privacy'],
  Composition: ['Foundation', 'Documents'],
  DocumentManifest: ['Foundation', 'Documents'],
  DocumentReference: ['Foundation', 'Documents'],
  CatalogEntry: ['Foundation', 'Documents'],
  Basic: ['Foundation', 'Other'],
  Binary: ['Foundation', 'Other'],
  Bundle: ['Foundation', 'Other'],
  Linkage: ['Foundation', 'Other'],
  MessageHeader: ['Foundation', 'Other'],
  OperationOutcome: ['Foundation', 'Other'],
  Parameters: ['Foundation', 'Other'],
  Subscription: ['Foundation', 'Other'],

  // Base
  Patient: ['Base', 'Individuals'],
  Practitioner: ['Base', 'Individuals'],
  PractitionerRole: ['Base', 'Individuals'],
  RelatedPerson: ['Base', 'Individuals'],
  Person: ['Base', 'Individuals'],
  Group: ['Base', 'Individuals'],
  Organization: ['Base', 'Entities'],
  OrganizationAffiliation: ['Base', 'Entities'],
  HealthcareService: ['Base', 'Entities'],
  Endpoint: ['Base', 'Entities'],
  Location: ['Base', 'Entities'],
  Substance: ['Base', 'Entities'],
  BiologicallyDerivedProduct: ['Base', 'Entities'],
  Device: ['Base', 'Entities'],
  DeviceMetric: ['Base', 'Entities'],
  Task: ['Base', 'Workflow'],
  Appointment: ['Base', 'Workflow'],
  AppointmentResponse: ['Base', 'Workflow'],
  Schedule: ['Base', 'Workflow'],
  Slot: ['Base', 'Workflow'],
  VerificationResult: ['Base', 'Workflow'],
  Encounter: ['Base', 'Management'],
  EpisodeOfCare: ['Base', 'Management'],
  Flag: ['Base', 'Management'],
  List: ['Base', 'Management'],

  // Clinical
  AllergyIntolerance: ['Clinical', 'Summary'],
  AdverseEvent: ['Clinical', 'Summary'],
  Condition: ['Clinical', 'Summary'],
  Procedure: ['Clinical', 'Summary'],
  FamilyMemberHistory: ['Clinical', 'Summary'],
  ClinicalImpression: ['Clinical', 'Summary'],
  DetectedIssue: ['Clinical', 'Summary'],
  Observation: ['Clinical', 'Diagnostics'],
  Media: ['Clinical', 'Diagnostics'],
  DiagnosticReport: ['Clinical', 'Diagnostics'],
  Specimen: ['Clinical', 'Diagnostics'],
  BodyStructure: ['Clinical', 'Diagnostics'],
  ImagingStudy: ['Clinical', 'Diagnostics'],
  QuestionnaireResponse: ['Clinical', 'Diagnostics'],
  MolecularSequence: ['Clinical', 'Diagnostics'],
  MedicationRequest: ['Clinical', 'Medications'],
  MedicationAdministration: ['Clinical', 'Medications'],
  MedicationDispense: ['Clinical', 'Medications'],
  MedicationStatement: ['Clinical', 'Medications'],
  Medication: ['Clinical', 'Medications'],
  MedicationKnowledge: ['Clinical', 'Medications'],
  Immunization: ['Clinical', 'Medications'],
  ImmunizationEvaluation: ['Clinical', 'Medications'],
  ImmunizationRecommendation: ['Clinical', 'Medications'],
  CarePlan: ['Clinical', 'Care Provision'],
  CareTeam: ['Clinical', 'Care Provision'],
  Goal: ['Clinical', 'Care Provision'],
  ServiceRequest: ['Clinical', 'Care Provision'],
  NutritionOrder: ['Clinical', 'Care Provision'],
  VisionPrescription: ['Clinical', 'Care Provision'],
  RiskAssessment: ['Clinical', 'Care Provision'],
  RequestGroup: ['Clinical', 'Care Provision'],
  Communication: ['Clinical', 'Request & Response'],
  CommunicationRequest: ['Clinical', 'Request & Response'],
  DeviceRequest: ['Clinical', 'Request & Response'],
  DeviceUseStatement: ['Clinical', 'Request & Response'],
  GuidanceResponse: ['Clinical', 'Request & Response'],
  SupplyRequest: ['Clinical', 'Request & Response'],
  SupplyDelivery: ['Clinical', 'Request & Response'],

  // Financial
  Coverage: ['Financial', 'Support'],
  CoverageEligibilityRequest: ['Financial', 'Support'],
  CoverageEligibilityResponse: ['Financial', 'Support'],
  EnrollmentRequest: ['Financial', 'Support'],
  EnrollmentResponse: ['Financial', 'Support'],
  Claim: ['Financial', 'Billing'],
  ClaimResponse: ['Financial', 'Billing'],
  Invoice: ['Financial', 'Billing'],
  PaymentNotice: ['Financial', 'Payment'],
  PaymentReconciliation: ['Financial', 'Payment'],
  Account: ['Financial', 'General'],
  ChargeItem: ['Financial', 'General'],
  ChargeItemDefinition: ['Financial', 'General'],
  Contract: ['Financial', 'General'],
  ExplanationOfBenefit: ['Financial', 'General'],
  InsurancePlan: ['Financial', 'General'],

  // Specialized
  ResearchStudy: ['Specialized', 'Public Health & Research'],
  ResearchSubject: ['Specialized', 'Public Health & Research'],
  ActivityDefinition: ['Specialized', 'Definitional Artifacts'],
  DeviceDefinition: ['Specialized', 'Definitional Artifacts'],
  EventDefinition: ['Specialized', 'Definitional Artifacts'],
  ObservationDefinition: ['Specialized', 'Definitional Artifacts'],
  PlanDefinition: ['Specialized', 'Definitional Artifacts'],
  Questionnaire: ['Specialized', 'Definitional Artifacts'],
  SpecimenDefinition: ['Specialized', 'Definitional Artifacts'],
  Library: ['Specialized', 'Definitional Artifacts'],
  ResearchDefinition: ['Specialized', 'Evidence-Based Medicine'],
  ResearchElementDefinition: ['Specialized', 'Evidence-Based Medicine'],
  Evidence: ['Specialized', 'Evidence-Based Medicine'],
  EvidenceVariable: ['Specialized', 'Evidence-Based Medicine'],
  EffectEvidenceSynthesis: ['Specialized', 'Evidence-Based Medicine'],
  RiskEvidenceSynthesis: ['Specialized', 'Evidence-Based Medicine'],
  Measure: ['Specialized', 'Quality Reporting & Testing'],
  MeasureReport: ['Specialized', 'Quality Reporting & Testing'],
  TestScript: ['Specialized', 'Quality Reporting & Testing'],
  TestReport: ['Specialized', 'Quality Reporting & Testing'],
  MedicinalProduct: ['Specialized', 'Medication Definition'],
  MedicinalProductAuthorization: ['Specialized', 'Medication Definition'],
  MedicinalProductContraindication: ['Specialized', 'Medication Definition'],
  MedicinalProductIndication: ['Specialized', 'Medication Definition'],
  MedicinalProductIngredient: ['Specialized', 'Medication Definition'],
  MedicinalProductInteraction: ['Specialized', 'Medication Definition'],
  MedicinalProductManufactured: ['Specialized', 'Medication Definition'],
  MedicinalProductPackaged: ['Specialized', 'Medication Definition'],
  MedicinalProductPharmaceutical: ['Specialized', 'Medication Definition'],
  MedicinalProductUndesirableEffect: ['Specialized', 'Medication Definition'],
  SubstanceNucleicAcid: ['Specialized', 'Medication Definition'],
  SubstancePolymer: ['Specialized', 'Medication Definition'],
  SubstanceProtein: ['Specialized', 'Medication Definition'],
  SubstanceReferenceInformation: ['Specialized', 'Medication Definition'],
  SubstanceSourceMaterial: ['Specialized', 'Medication Definition'],
  SubstanceSpecification: ['Specialized', 'Medication Definition'],
}

export function categorize(type: string): { category: string; subcategory: string } {
  const entry = MAP[type]
  if (!entry) return { category: 'Other', subcategory: 'Uncategorized' }
  return { category: entry[0], subcategory: entry[1] }
}

export function isMapped(type: string): boolean {
  return type in MAP
}
