/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimClaimTypeRouteImport } from './routes/claim.$claimType'
import { Route as FieldFieldIdRouteImport } from './routes/field.$fieldId'
import { Route as R4IndexRouteImport } from './routes/r4.index'
import { Route as R4TypeRouteImport } from './routes/r4.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimClaimTypeRoute = ClaimClaimTypeRouteImport.update({
  id: '/claim/$claimType',
  path: '/claim/$claimType',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldFieldIdRoute = FieldFieldIdRouteImport.update({
  id: '/field/$fieldId',
  path: '/field/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const R4IndexRoute = R4IndexRouteImport.update({
  id: '/r4/',
  path: '/r4/',
  getParentRoute: () => rootRouteImport,
} as any)
const R4TypeRoute = R4TypeRouteImport.update({
  id: '/r4/$type',
  path: '/r4/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim/$claimType': typeof ClaimClaimTypeRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/r4/$type': typeof R4TypeRoute
  '/r4/': typeof R4IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim/$claimType': typeof ClaimClaimTypeRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/r4/$type': typeof R4TypeRoute
  '/r4': typeof R4IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim/$claimType': typeof ClaimClaimTypeRoute
  '/field/$fieldId': typeof FieldFieldIdRoute
  '/r4/$type': typeof R4TypeRoute
  '/r4/': typeof R4IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/claim/$claimType' | '/field/$fieldId' | '/r4/$type' | '/r4/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claim/$claimType' | '/field/$fieldId' | '/r4/$type' | '/r4'
  id:
    | '__root__'
    | '/'
    | '/claim/$claimType'
    | '/field/$fieldId'
    | '/r4/$type'
    | '/r4/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimClaimTypeRoute: typeof ClaimClaimTypeRoute
  FieldFieldIdRoute: typeof FieldFieldIdRoute
  R4TypeRoute: typeof R4TypeRoute
  R4IndexRoute: typeof R4IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$claimType': {
      id: '/claim/$claimType'
      path: '/claim/$claimType'
      fullPath: '/claim/$claimType'
      preLoaderRoute: typeof ClaimClaimTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/$fieldId': {
      id: '/field/$fieldId'
      path: '/field/$fieldId'
      fullPath: '/field/$fieldId'
      preLoaderRoute: typeof FieldFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r4/': {
      id: '/r4/'
      path: '/r4'
      fullPath: '/r4/'
      preLoaderRoute: typeof R4IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r4/$type': {
      id: '/r4/$type'
      path: '/r4/$type'
      fullPath: '/r4/$type'
      preLoaderRoute: typeof R4TypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimClaimTypeRoute: ClaimClaimTypeRoute,
  FieldFieldIdRoute: FieldFieldIdRoute,
  R4TypeRoute: R4TypeRoute,
  R4IndexRoute: R4IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
